image: node:7

stages:
  - test
  - coverage

cache:   
  paths:   
    - node_modules/

npm_test:
  stage: test
  script: 
    - npm install -g jshint node-gyp
    - yarn install
    - make all

coverage:
  stage: coverage
  script:
    - npm install -g istanbul
    - make coverage
