image: node:7

stages:
  - test

cache:   
  paths:   
    - node_modules/

npm_test:
  stage: test
  script: 
    - npm install -g jshint
    - make lint
    - npm install
    - npm test

after_script:
  - ls -la
