language: node_js

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

env:
  - CXX=g++-4.8

node_js:
  - "0.10"
  - "0.12"
  - "4"

cache:
  directories:
    - node_modules

before_install:
  - npm install -g jshint

script:
  - make
